In [81]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris



In [82]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = (iris.target == 0).astype(int)  # Setosa vs. non-Setosa


In [83]:
X = tf.random.uniform((100, 2))
y = (X + 5) * 0.3

In [84]:
type(X), type(y)

(tensorflow.python.framework.ops.EagerTensor,
 tensorflow.python.framework.ops.EagerTensor)

In [85]:
X.shape, y.shape

(TensorShape([100, 2]), TensorShape([100, 2]))

# Define a simple Neural Network 

In [86]:
model =  tf.keras.Sequential([
    tf.keras.layers.Input(name="InputLayer", shape=[2]),
    tf.keras.layers.Dense(2, name="Layer1"),
    #tf.keras.layers.Dense(2, name="Layer2"),
 ])

In [87]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Layer1 (Dense)              (None, 2)                 6         
                                                                 
Total params: 6 (24.00 Byte)
Trainable params: 6 (24.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [88]:
model.layers[0].weights

[<tf.Variable 'Layer1/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-1.0160371 ,  0.77473927],
        [ 1.0257031 ,  0.24407482]], dtype=float32)>,
 <tf.Variable 'Layer1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

# Train Neural Network 

In [89]:
model.compile(loss="MSE", optimizer="adam")

In [90]:
model.fit(X, y, epochs=100)

Epoch 1/100
4/4 [==============================] - 3s 6ms/step - loss: 2.1474
Epoch 2/100
4/4 [==============================] - 0s 7ms/step - loss: 2.1252
Epoch 3/100
4/4 [==============================] - 0s 7ms/step - loss: 2.1033
Epoch 4/100
4/4 [==============================] - 0s 21ms/step - loss: 2.0816
Epoch 5/100
4/4 [==============================] - 0s 9ms/step - loss: 2.0601
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 2.0385
Epoch 7/100
4/4 [==============================] - 0s 16ms/step - loss: 2.0175
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 1.9965
Epoch 9/100
4/4 [==============================] - 0s 7ms/step - loss: 1.9758
Epoch 10/100
4/4 [==============================] - 0s 6ms/step - loss: 1.9554
Epoch 11/100
4/4 [==============================] - 0s 17ms/step - loss: 1.9348
Epoch 12/100
4/4 [==============================] - 0s 12ms/step - loss: 1.9145
Epoch 13/100
4/4 [==============================] - 0s 13

In [91]:
model.weights

[<tf.Variable 'Layer1/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.6680302 ,  1.0803027 ],
        [ 1.3650491 ,  0.56320405]], dtype=float32)>,
 <tf.Variable 'Layer1/bias:0' shape=(2,) dtype=float32, numpy=array([0.35195565, 0.3297612 ], dtype=float32)>]

In [92]:
l = model.layers[0]

In [93]:
l.weights

[<tf.Variable 'Layer1/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.6680302 ,  1.0803027 ],
        [ 1.3650491 ,  0.56320405]], dtype=float32)>,
 <tf.Variable 'Layer1/bias:0' shape=(2,) dtype=float32, numpy=array([0.35195565, 0.3297612 ], dtype=float32)>]

In [94]:
(20.0 * l.weights[0][0]) + (3.0 * l.weights[0][1]) + ( l.weights[1])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-8.913502, 23.625427], dtype=float32)>

In [95]:
model.predict([[20.0, 3.0]])

1/1 [==============================] - 0s 351ms/step


array([[-8.913502, 23.625427]], dtype=float32)

# Plot the model

In [96]:
tf.keras.utils.plot_model(model)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.
