In [45]:
import tensorflow as tf
import numpy as np

# Define a simple dummy dataset

In [46]:
X = tf.random.uniform((1000, 1))
y = (X +500) * 20
X

<tf.Tensor: shape=(1000, 1), dtype=float32, numpy=
array([[2.87896276e-01],
       [6.72964454e-01],
       [1.95893884e-01],
       [2.30957627e-01],
       [2.13873029e-01],
       [8.58161926e-01],
       [5.86790800e-01],
       [7.24792361e-01],
       [5.50635338e-01],
       [4.01531339e-01],
       [6.68829322e-01],
       [2.34091043e-01],
       [5.90113521e-01],
       [3.13114166e-01],
       [6.70956373e-01],
       [8.76943827e-01],
       [5.89424372e-02],
       [5.46825528e-01],
       [1.13777995e-01],
       [8.71264458e-01],
       [8.92744660e-01],
       [5.69991946e-01],
       [4.83110547e-01],
       [1.66255116e-01],
       [9.78966117e-01],
       [4.17887092e-01],
       [1.53510332e-01],
       [2.73530245e-01],
       [7.07333684e-01],
       [9.06116962e-01],
       [2.59074330e-01],
       [3.06410074e-01],
       [8.28871369e-01],
       [6.79955959e-01],
       [5.76689839e-01],
       [2.42715240e-01],
       [9.19970512e-01],
       [5.22875547e-01],

In [47]:
type(X), type(y)

(tensorflow.python.framework.ops.EagerTensor,
 tensorflow.python.framework.ops.EagerTensor)

In [48]:
X.shape, y.shape

(TensorShape([1000, 1]), TensorShape([1000, 1]))

# Define a simple Neural Network 

In [84]:
"""
model =  tf.keras.Sequential([
    tf.keras.layers.Input(name="InputLayer", shape=[1]),
    tf.keras.layers.Dense(100, name="Layer1"),
    tf.keras.layers.Dense(1, name="Layer2"),
 ])

model =  tf.keras.Sequential([
    tf.keras.layers.Input(name="InputLayer", shape=[1]),
    tf.keras.layers.Dense(100, name="Layer1"),
    tf.keras.layers.Dense(100, name="Layer2"),
    tf.keras.layers.Dense(100, name="Layer3"),
    tf.keras.layers.Dense(1, name="outputLayer"),
 ])
"""

model =  tf.keras.Sequential([
    tf.keras.layers.Input(name="InputLayer", shape=[1]),
    tf.keras.layers.Dense(100, name="Layer1"),
    tf.keras.layers.Dense(50, name="Layer2"),
    tf.keras.layers.Dense(20, name="Layer3"),
    tf.keras.layers.Dense(1, name="outputLayer"),
 ])
"""
model =  tf.keras.Sequential([
    tf.keras.layers.Input(name="InputLayer", shape=[1]),
    tf.keras.layers.Dense(1000, name="Layer1"),
    tf.keras.layers.Dense(500, name="Layer2"),
    tf.keras.layers.Dense(100, name="Layer3"),
    tf.keras.layers.Dense(1, name="outputLayer"),
 ])
"""

'\nmodel =  tf.keras.Sequential([\n    tf.keras.layers.Input(name="InputLayer", shape=[1]),\n    tf.keras.layers.Dense(1000, name="Layer1"),\n    tf.keras.layers.Dense(500, name="Layer2"),\n    tf.keras.layers.Dense(100, name="Layer3"),\n    tf.keras.layers.Dense(1, name="outputLayer"),\n ])\n'

In [85]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Layer1 (Dense)              (None, 100)               200       
                                                                 
 Layer2 (Dense)              (None, 50)                5050      
                                                                 
 Layer3 (Dense)              (None, 20)                1020      
                                                                 
 outputLayer (Dense)         (None, 1)                 21        
                                                                 
Total params: 6291 (24.57 KB)
Trainable params: 6291 (24.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [86]:
model.layers[0].weights[0].shape

TensorShape([1, 100])

# Train Neural Network 

In [87]:
model.compile(loss="MSE", optimizer="adam")

In [88]:
model.fit(X, y, epochs=100)

Epoch 1/100
32/32 [==============================] - 1s 3ms/step - loss: 100160264.0000
Epoch 2/100
32/32 [==============================] - 0s 3ms/step - loss: 99838608.0000
Epoch 3/100
32/32 [==============================] - 0s 3ms/step - loss: 98205688.0000
Epoch 4/100
32/32 [==============================] - 0s 2ms/step - loss: 92721200.0000
Epoch 5/100
32/32 [==============================] - 0s 2ms/step - loss: 79572096.0000
Epoch 6/100
32/32 [==============================] - 0s 2ms/step - loss: 56484396.0000
Epoch 7/100
32/32 [==============================] - 0s 2ms/step - loss: 28306650.0000
Epoch 8/100
32/32 [==============================] - 0s 2ms/step - loss: 9168821.0000
Epoch 9/100
32/32 [==============================] - 0s 2ms/step - loss: 4437317.0000
Epoch 10/100
32/32 [==============================] - 0s 2ms/step - loss: 4092624.7500
Epoch 11/100
32/32 [==============================] - 0s 2ms/step - loss: 3844818.0000
Epoch 12/100
32/32 [========================

32/32 [==============================] - 0s 2ms/step - loss: 1.9346e-05
Epoch 98/100
32/32 [==============================] - 0s 2ms/step - loss: 1.7129e-05
Epoch 99/100
32/32 [==============================] - 0s 2ms/step - loss: 1.5820e-05
Epoch 100/100
32/32 [==============================] - 0s 2ms/step - loss: 1.4648e-05


In [89]:
#(20.0 * model.weights[0][0]) + (3.0 * model.weights[0][1]) + ( model.weights[1])

# Plot the model

In [90]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Layer1 (Dense)              (None, 100)               200       
                                                                 
 Layer2 (Dense)              (None, 50)                5050      
                                                                 
 Layer3 (Dense)              (None, 20)                1020      
                                                                 
 outputLayer (Dense)         (None, 1)                 21        
                                                                 
Total params: 6291 (24.57 KB)
Trainable params: 6291 (24.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [91]:
tf.keras.utils.plot_model(model)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


# Predict 

In [92]:
model.predict([[9]])

1/1 [==============================] - 0s 87ms/step


array([[10180.1]], dtype=float32)

In [93]:
(np.array([9]) + 500) * 20

array([10180])